muziq/web/views/artist.py
import os
import json
import urllib2
from sqlalchemy import sql, distinct
from sqlalchemy.orm import joinedload, subqueryload, subqueryload_all
from lxml import etree
from flask import Blueprint, g, request, abort, render_template, make_response, current_app, url_for
from muziq import tables as t
from muziq import db
from muziq.models import Artist, ArtistCredit, ArtistCreditName, Release, MedialibRelease
from muziq.web.utils import cache_image

artist_pages = Blueprint('artist', __name__)


@artist_pages.route('/<string:id>')
def index(id):
    artist = db.session.query(Artist).filter_by(gid=id).first()
    if artist is None:
        return abort(404)

    artist_credits = db.session.query(ArtistCreditName.artist_credit_id).\
        filter(ArtistCreditName.artist_id == artist.id).\
        subquery()

    medialib_releases = db.session.query(MedialibRelease.mb_release_id).\
        subquery()

    releases = db.session.query(Release).\
        filter(Release.artist_credit_id.in_(artist_credits)).\
        filter(Release.gid.in_(medialib_releases)).\
        options(joinedload('artist_credit')).\
        options(subqueryload('artist_credit.artists')).\
        all()

    return render_template('artist.html', artist=artist, releases=releases)


@artist_pages.route('/<string:id>/image')
@artist_pages.route('/<string:id>/image/<int:size>')
def image(id, size=500):
    cache_dir = os.path.join(current_app.config['CACHE_DIR'], 'artist_image')
    fallback_url = url_for('static', filename='no-cover.png')

    def fetch_artist_image():
        url = 'http://api.fanart.tv/webservice/artist/%s/%s/JSON/artistthumb/1/1/' % (current_app.config['FANART_API_KEY'], id)
        try:
            artists = json.load(urllib2.urlopen(url))
        except urllib2.URLError:
            return None

        if not artists:
            return None

        images = artists.values()[0]['artistthumb']
        if not images:
            return None

        try:
            return urllib2.urlopen(images[0]['url'])
        except urllib2.URLError:
            return None

    return cache_image(cache_dir, fetch_artist_image, fallback_url, id, size)


def foo():
    source = t.artist.\
        join(t.artist_name, t.artist.c.name_id == t.artist_name.c.id)
    query = sql.select([
        t.artist.c.gid.label('id'),
        t.artist_name.c.name,
    ], from_obj=source)
    query = query.where(t.artist.c.gid == id)
    artist = g.db.execute(query).fetchone()
    if artist is None:
        return abort(404)

    source = t.release_group.\
        join(t.release_name, t.release_group.c.name_id == t.release_name.c.id).\
        join(t.release_group_meta, t.release_group.c.id == t.release_group_meta.c.id).\
        join(t.release_group_primary_type, t.release_group.c.type_id == t.release_group_primary_type.c.id).\
        join(t.artist_credit_name, t.release_group.c.artist_credit_id == t.artist_credit_name.c.artist_credit_id).\
        join(t.artist, t.artist_credit_name.c.artist_credit_id == t.artist.c.id)
    query = sql.select([
        t.release_group.c.gid.label('id'),
        t.release_name.c.name,
        t.release_group_primary_type.c.name.label('type'),
        t.release_group_meta.c.first_release_date_year,
        t.release_group_meta.c.first_release_date_month,
        t.release_group_meta.c.first_release_date_day,
    ], from_obj=source)
    query = query.where(t.artist.c.gid == id)
    query = query.where(t.release_group_meta.c.first_release_date_year != None)
    query = query.order_by(
        t.release_group_meta.c.first_release_date_year.desc(),
        t.release_group_meta.c.first_release_date_month.desc(),
        t.release_group_meta.c.first_release_date_day.desc())
    limit = min(100, request.args.get('limit', 100, type=int))
    query = query.limit(limit)
    albums = g.db.execute(query).fetchall()

    return render_template('artist.html', artist=artist, albums=albums)


@artist_pages.route('/<string:id>/new-releases.rss')
def new_releases_rss(id):
    source = t.release_group.\
        join(t.release_name, t.release_group.c.name_id == t.release_name.c.id).\
        join(t.release_group_meta, t.release_group.c.id == t.release_group_meta.c.id).\
        join(t.release_group_primary_type, t.release_group.c.type_id == t.release_group_primary_type.c.id).\
        join(t.artist_credit_name, t.release_group.c.artist_credit_id == t.artist_credit_name.c.artist_credit_id).\
        join(t.artist, t.artist_credit_name.c.artist_credit_id == t.artist.c.id)
    query = sql.select([
        t.release_group.c.gid,
        t.release_name.c.name,
        t.release_group_primary_type.c.name.label('type'),
        t.release_group_meta.c.first_release_date_year,
        t.release_group_meta.c.first_release_date_month,
        t.release_group_meta.c.first_release_date_day,
    ], from_obj=source)
    query = query.where(t.artist.c.gid == id)
    query = query.where(t.release_group_meta.c.first_release_date_year != None)
    query = query.order_by(
        t.release_group_meta.c.first_release_date_year.desc(),
        t.release_group_meta.c.first_release_date_month.desc(),
        t.release_group_meta.c.first_release_date_day.desc())
    limit = min(100, request.args.get('limit', 10, type=int))
    query = query.limit(limit)
    feed = etree.Element('feed', nsmap={None: 'http://www.w3.org/2005/Atom'})
    etree.SubElement(feed, 'title').text = 'New Releases'
    for row in g.db.execute(query):
        entry = etree.SubElement(feed, 'entry')
        etree.SubElement(entry, 'title').text = '%s %s [%s] [%s]' % ('', row['name'], row['first_release_date_year'], row['type'])
        url = 'http://muziq.eu/album/' + row['gid']
        etree.SubElement(entry, 'link', href=url)
    return etree.tostring(feed, pretty_print=True)

muziq/web/views/files.py
from sqlalchemy import sql, distinct
from sqlalchemy.orm import joinedload, subqueryload, subqueryload_all
from flask import Blueprint, g, request, abort, render_template, make_response
from muziq import db
from muziq.models import MedialibFile, MedialibDirectory

files_pages = Blueprint('files', __name__)


@files_pages.route('/')
@files_pages.route('/<int:directory_id>')
def index(directory_id=None):
    if directory_id is None:
        directory = db.session.query(MedialibDirectory).filter_by(parent=None, name='').one()
    else:
        directory = db.session.query(MedialibDirectory).get(directory_id)

    directories = db.session.query(MedialibDirectory).filter_by(parent=directory).order_by(MedialibDirectory.name)
    files = db.session.query(MedialibFile).filter_by(parent=directory).order_by(MedialibFile.name)

    return render_template('files.html', directory=directory, directories=directories, files=files)

muziq/web/views/release.py
import os
import urllib2
import shutil
import subprocess
from lxml import etree
from sqlalchemy.orm import joinedload, subqueryload, subqueryload_all, joinedload_all
from flask import Blueprint, g, request, abort, render_template, make_response, send_file, url_for, redirect, current_app
from muziq import db
from muziq.models import Release, MedialibFile, CoverArt
from muziq.web.utils import cache_image

release_pages = Blueprint('release', __name__)


@release_pages.route('/<string:id>')
def index(id):
    release = db.session.query(Release).filter_by(gid=id).\
        options(joinedload('artist_credit')).\
        options(subqueryload('artist_credit.artists')).\
        options(joinedload('mediums.tracks.artist_credit')).\
        options(subqueryload_all('mediums.tracks.artist_credit.artists')).\
        first()
    if release is None:
        return abort(404)

    files = db.session.query(MedialibFile).filter_by(mb_release=id).all()

    return render_template('release.html', release=release, files=files)


@release_pages.route('/<string:id>/cover-art')
@release_pages.route('/<string:id>/cover-art/<int:size>')
def cover_art(id, size=500):
    cache_dir = os.path.join(current_app.config['CACHE_DIR'], 'cover_art')
    fallback_url = url_for('static', filename='no-cover.png')

    def fetch_cover_art():
        #has_cover_art = db.session.query(CoverArt).join(Release).filter_by(gid=id).count()
        #if not has_cover_art:
        #    return None

        url = 'http://coverartarchive.org/release/%s/front' % id
        try:
            return urllib2.urlopen(url)
        except urllib2.URLError:
            return None

    return cache_image(cache_dir, fetch_cover_art, fallback_url, id, size)


@release_pages.route('/release/<string:id>.xspf')
def xspf(id):
    release = db.session.query(Release).filter_by(gid=id).\
        options(joinedload('artist_credit')).\
        options(joinedload('artist_credit.name')).\
        options(subqueryload_all('mediums.tracks.artist_credit.name')).\
        options(subqueryload_all('mediums.tracks.recording')).\
        first()
    if release is None:
        return abort(404)

    files = db.session.query(MedialibFile).filter_by(mb_release=id).\
        order_by(MedialibFile.mb_medium_no, MedialibFile.mb_track_no)

    files_index = {}
    for file in files:
        files_index.setdefault(file.mb_recording, []).append(file)

    playlist_el = etree.Element('playlist', {'version': '1'}, nsmap={None: 'http://xspf.org/ns/0/'})
    etree.SubElement(playlist_el, 'title').text = release.name.name
    etree.SubElement(playlist_el, 'creator').text = release.artist_credit.name.name
    etree.SubElement(playlist_el, 'info').text = url_for('release.index', id=id, _external=True)

    tracklist_el = etree.SubElement(playlist_el, 'trackList')
    for medium in release.mediums:
        for track in medium.tracks:
            track_el = etree.SubElement(tracklist_el, 'track')
            etree.SubElement(track_el, 'title').text = track.name.name
            etree.SubElement(track_el, 'creator').text = track.artist_credit.name.name
            etree.SubElement(track_el, 'album').text = release.name.name
            files = files_index.get(track.recording.gid)
            if files is None:
                continue
            for file in files:
                if file.mb_medium_no == medium.position and file.mb_track_no == track.position:
                    break
            etree.SubElement(track_el, 'location').text = url_for('media.file', id=file.id, _external=True)

    response = make_response(etree.tostring(playlist_el, pretty_print=True))
    response.headers['Content-Type'] = 'application/xspf+xml; charset=UTF-8'
    response.headers['Content-Disposition'] = 'attachment; filename="muziq-%s.xspf"' % id
    return response

muziq/web/templates/artist.html
{% import "macros.html" as macros %}
{% extends "layout.html" %}
{% block content %}

<h1>{{ artist.name.name }}</h1>

<div class="row">
  <div class="span3">
    <p><img src="{{ url_for('artist.image', id=artist.gid, size=270) }}" href="Picture of {{ artist.name.name }}" width="270" height="270" /></p>
    <p class="muted">See this artist at <a href="//musicbrainz.org/artist/{{ artist.gid }}">MusicBrainz</a></p>
  </div>
  <div class="span9">

<table class="table table-condensed table-releases">
  <tbody>
    {% for release in releases %}
    <tr>
      <td class="column-cover"><img src="{{ url_for('release.cover_art', id=release.gid, size=50) }}" width="50" height="50" /></td>
      <td><a href="{{ url_for('release.index', id=release.gid) }}">{{ release.name.name }}</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

    </div>

</div>


{% endblock %}

muziq/web/templates/files.html
{% import "macros.html" as macros %}
{% extends "layout.html" %}
{% block content %}

<h1>{{ directory.name }}</h1>

<table class="table table-striped table-condensed">
  <tbody>
    {% for directory in directories %}
      <tr>
        <td><i class="icon-folder-open"></i> <a href="{{ url_for('files.index', directory_id=directory.id) }}">{{ directory.name }}</a></td>
      <td>
    {% endfor %}
    {% for file in files %}
      <tr>
        <td><i class="icon-file"></i> {{ file.name }}</td>
      <td>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

muziq/web/templates/index.html
{% import "macros.html" as macros %}
{% extends "layout.html" %}
{% block content %}

<div class="row">

  <div class="span6">
    <h1>Recently Added Releases</h1>
    <table class="table table-condensed table-releases">
      <tbody>
        {% for release in last_added_releases %}
        <tr>
          <td class="column-cover"><img src="{{ url_for('release.cover_art', id=release.mb_release.gid, size=50) }}" width="50" height="50" /></td>
          <td>{{ macros.render_artist_credit(release.mb_release.artist_credit) }} &ndash; <a href="{{ url_for('release.index', id=release.mb_release_id) }}">{{ release.mb_release.name.name }}</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="span6">
    <h1>Random Releases</h1>
    <table class="table table-condensed table-releases">
      <tbody>
        {% for release in random_releases %}
        <tr>
          <td class="column-cover"><img src="{{ url_for('release.cover_art', id=release.mb_release.gid, size=50) }}" width="50" height="50" /></td>
          <td>{{ macros.render_artist_credit(release.mb_release.artist_credit) }} &ndash; <a href="{{ url_for('release.index', id=release.mb_release_id) }}">{{ release.mb_release.name.name }}</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

</div>

{% endblock %}

muziq/web/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% if self.title() %}{% block title %}{% endblock %} - {% endif %}Musiqué</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for_static('bootstrap/css/bootstrap.min.css') }}" media="screen">
    <link rel="stylesheet" href="{{ url_for_static('bootstrap/css/bootstrap-responsive.min.css') }}" media="screen">
    <link rel="stylesheet/less" href="{{ url_for_static('muziq.less') }}">
    <script src="{{ url_for_static('less-1.3.0.min.js') }}"></script>
	<script src="{{ url_for_static('jquery-1.10.0.min.js') }}"></script>
    <script src="{{ url_for_static('bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for_static('muziq.js') }}"></script>
</head>
<body>

    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="brand" href="{{ url_for('index') }}">MZQ</a>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li class="active"><a href="{{ url_for('index') }}">Home</a></li>
                        <li><a href="{{ url_for('files.index') }}">Files</a></li>
                        <li><a href="#radio">Radio</a></li>
                    </ul>
                </div>
            </div>
        </div>    
    </div>

	<div id="wrap">
        <div class="container">
            {% block content %}{% endblock %}
        </div>
        <div id="push"></div>
    </div>

    <div id="footer">
	    <div class="container">
            <p class="muted credit">
                Created by <a href="http://oxygene.sk/">Lukáš Lalinský</a> | Music metadata provided by <a href="http://musicbrainz.org/">MusicBrainz</a> | Audio played using <a href="http://www.videolan.org/vlc/">VideoLAN media player</a>
            </p>
        </div>
    </div>

</body>
</html>

muziq/web/templates/macros.html
{%- macro render_artist_credit(artist_credit) -%}
  {%- for artist_credit_name in artist_credit.artists -%}
    <a href="{{ url_for('artist.index', id=artist_credit_name.artist.gid) }}">{{ artist_credit_name.name.name }}</a>{{ artist_credit_name.join_phrase }}
  {%- endfor -%}
{%- endmacro -%}

muziq/web/templates/release.html
{% import "macros.html" as macros %}
{% extends "layout.html" %}
{% block content %}

<h1>{{ macros.render_artist_credit(release.artist_credit) }} &ndash; {{ release.name.name }}</h1>

<div class="row">
  <div class="span3">
    <p><img src="{{ url_for('release.cover_art', id=release.gid, size=270) }}" href="Cover art for release {{ release.name.name }}" width="270" height="270" /></p>
    <p>
      {% if files %}
      <a class="btn btn-small vlc-play-xspf" href="{{ url_for('release.xspf', id=release.gid, _external=True) }}"><i class="icon-play"></i> Play</a>
      <a class="btn btn-small" href="{{ url_for('release.xspf', id=release.gid) }}"><i class="icon-download-alt"></i> Download</a>
      {% endif %}
    </p>
    <p>
      <b>{{ release.name.name }}</b><br>
      {{ macros.render_artist_credit(release.artist_credit) }}
    </p>
    <p class="muted">See this release at <a href="//musicbrainz.org/release/{{ release.gid }}">MusicBrainz</a></p>
  </div>
  <div class="span9">

<table class="table table-striped table-condensed table-release">
{% for medium in release.mediums %}
    <thead>
        <tr>
            <th></th>
            <th colspan="2">Medium {{ medium.position }}</th>
        <tr>
    </thead>
    <tbody>
      {% for track in medium.tracks %}
        <tr>
            <td class="column-track muted">{{ track.position }}.</td>
            <td class="column-title">
                {{ track.name.name }}
                {% if track.artist_credit_id != release.artist_credit_id %}
                   <br><small> &ndash; {{ macros.render_artist_credit(track.artist_credit) }}</small>
                {% endif %}
            </td>
            <td class="column-length muted">{{ track.length | lengthformat }}</td>
        </tr>
    {% endfor %}
    </tbody>
{% endfor %}
</table>
    </div>

</div>

{% endblock %}

muziq/web/templates/search.html
{% extends "layout.html" %}
{% block title %}Search results for "{{ query }}"{% endblock %}
{% block content %}

<h1>Search results for "{{ query }}"</h1>

{% for result in results %}
<p>
	{% if result.kind == 'artist' %}
	Artist: <a href="{{ url_for('artist.index', id=result.id) }}">{{ result.name }}</a>
	{% else %}
	<a href="{{ result.url }}">{{ result.name }}</a>
	{% endif %}
</p>
{% endfor %}

{% endblock %}